

def init_handler(global_headers, global_post_param, global_query_param):
    global_headers['X-REST-API'] = 'testing'
    return True


TEST_ENV = {
    'project_name': 'CloudMagic APIs',
    'global_headers': {},
    'global_post_param': {},
    'global_query_param': {},
    'init_hooks': init_handler,
    'global_info': {},
    'smtp_setting': {'host': '10.1.0.162',
                      'to': ['anurag.shukla@webyog.com', 'ritayan.das@webyog.com', 'mitchell.thomas@webyog.com']},
    'domain': 'api.cloudmagic.com',
    'protocol': 'https',
    'testcases': [
        'cases.login.py',
        'cases.test1.py',
        'cases.test2.py',
        'cases.test3.py',
        'cases.test4.py',
        'cases.test5.py',
        'cases.test6.py',
        'cases.test7.py',
        'cases.test8.py',
        'cases.test9.py',
        'cases.test10.py',
        'cases.test11.py',
        'cases.test12.py',
        'cases.test13.py',
        'cases.test14.py',
        'cases.test15.py',
        'cases.test16.py',
        'cases.test17.py',
        'cases.test18.py',
        'cases.test19.py',
        'cases.test20.py',
        'cases.test21.py',
        'cases.test23.py',
        'cases.test25.py',
        'cases.test26.py',
        'cases.test27.py',
        'cases.test28.py',
        'cases.test29.py',
        'cases.test30.py',
        'cases.test31.py',
        'cases.test32.py',
        'cases.test33.py',
        'cases.test34.py',
        'cases.test35.py',
        'cases.test36.py',
        'cases.test37.py',
        'cases.test38.py',
        'cases.test39.py',
        'cases.test40.py',
        'cases.test41.py',
        'cases.test42.py',
    ]
}
